# Generated by Django 3.1.6 on 2021-02-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0005_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_side', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_bottom', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offer.offercategory')),
            ],
        ),
    ]
