# Generated by Django 3.1.6 on 2021-02-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
