# Generated by Django 3.1.6 on 2021-02-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaicon',
            old_name='url',
            new_name='social_url',
        ),
    ]
