# Generated by Django 3.1.6 on 2021-02-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
        migrations.CreateModel(
            name='InfoLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='info.info')),
            ],
        ),
    ]
